/*
 * Header file for disaggregated architecture simulation.
 */
#ifndef __DSAG_MEM_SIMULATE_H
#define __DSAG_MEM_SIMULATE_H

#ifdef CONFIG_KVM_DSAG_MEM_SIMULATION

#define DSAG_LOCAL_MEMORY_SIZE (1UL << DSAG_LOCAL_MEMORY_SHIFT)
#define DSAG_LOCAL_MEMORY_SHIFT 22
#define DSAG_LOCAL_MEMORY_PAGE_NUM \
    (1UL << (DSAG_LOCAL_MEMORY_SHIFT - PAGE_SHIFT))
#define DSAG_MEM_HASH_BITS (DSAG_LOCAL_MEMORY_SHIFT - PAGE_SHIFT)

#endif  // CONFIG_KVM_DSAG_MEM_SIMULATION
#endif  // __DSAG_MEM_SIMULATE_H
